### ISSUE TITLE
[feat #1] 관리자 회원가입, 로그인 (JWT) 

### ISSUE THREAD

**Issue by seyoung5744** [seyoung5744/Musinsa-Monitor#1]
## 📌 Description

> 회원 가입과 로그인 기능 구
> API 형태로 제공을 위해 JWT 토큰 사용

**Refresh Token 도입**
access token은 JWT이므로 그 자체로 인증 정보를 모두 가지고 있어서 탈취되면 매우 위험한 상황이 발생. 
access token은 서버에 저장되지 않으므로(stateless) token이 탈취되면 서버에서는 막을 방법이 없음.
accessToken의 만료 시 새로 토큰을 발급해주는 용도로 refresh token을 사용.
refresh Token은 자주 읽어와야 하는 존재이므로 RDS가 아닌 Redis에서 관리

<br>

## 📝 To-do
- [ ] 회원 가입
- [ ] 이메일 중복 검사
- [ ] 인증 메일 발송
- [ ] JWT 토큰 생성
- [ ] JWT 토큰 검증
- [ ]  Refresh Token 생성 및 Redis에 저장

<br>

## 🤝 관련 이슈
- #ISSUE_NUMBER

<br>

#### Reference
refresh token 사용 전
[https://velog.io/@sysy123/Spring-Boot-Spring-Security-JWT-회원가입로그인](https://velog.io/@sysy123/Spring-Boot-Spring-Security-JWT-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85%EB%A1%9C%EA%B7%B8%EC%9D%B8)
refresh token 사용 후
[https://velog.io/@park2348190/JWT에서-Refresh-Token은-왜-필요한가](https://velog.io/@park2348190/JWT%EC%97%90%EC%84%9C-Refresh-Token%EC%9D%80-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80)
https://gksdudrb922.tistory.com/217
(Redis + Refresh) https://sol-devlog.tistory.com/22
<br>

#### ETC
기타사항

<br>

### ✅ 체크 리스트
- [ ] issue 제목은 유의미한가?
- [ ] issue 내용은 모르는 사람도 파악할 수 있을 정도로 기술되었는가?
- [ ] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [ ] 유의미한 label을 추가했는가?

---
