### ISSUE TITLE
[feat] 회원 관리 기능

### ISSUE THREAD

**Issue by seyoung5744** [seyoung5744/Musinsa-Monitor#2]
## 📌 Description
**JWT 활용한 회원 관리 기능**
- 회원 가입
- 로그인
- 회원 탈퇴

<br>

## 📝 To-do
- [ ] 회원 가입 
- [ ] 로그인 
- [ ] 회원 탈퇴 
- [ ] 이메일 인증
- [x] 이메일 중복 검사
- [ ] JWT 토큰 발행
- [ ] JWT 토큰 인증

---
