### ISSUE TITLE
[feat] 개발 환경 구축

### ISSUE THREAD

**Issue by seyoung5744** [seyoung5744/Musinsa-Monitor#3]
## 📌 Description
- 전체적인 Error 코드 Global 관리
- logback으로 로그 관리
- Api Document Setting
- Api Response 인터페이스로 관리하기

<br>

## 📝 To-do
- [x]  Error 코드 Global 관리
- [ ] logback으로 로그 관리
- [ ] Api Document Setting
- [x] Api Response 인터페이스

---
